spring.application.name=demo

# database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/gamelog
spring.datasource.username=gamelog
spring.datasource.password=gamelog

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# security
spring.security.user.name=admin
spring.security.user.password=123456
spring.security.user.roles=ADMIN