spring.application.name=demo
spring.config.import=optional:file:.env[.properties]

# database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/gamelog
spring.datasource.username=gamelog
spring.datasource.password=gamelog

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# security
gamelog.jwt.segredo=${GAMELOG_JWT_SEGREDO}
gamelog.jwt.expiracao=24h
# cookie false so para desenvolvimento, em prod deve ser true
gamelog.cookie.secure=false
spring.mvc.problemdetails.enabled=true